import { cn } from '@/lib/utils'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { HTMLAttributes } from 'react'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <Container>
            {children}
          </Container>
        </main>
      </body>
    </html>
  )
}


function Container({ children, className, ...rest }: HTMLAttributes<HTMLDivElement>) {
  return (
    <section className={cn('p-4', className)} {...rest}>
      {children}
    </section>
  )
}